version: '3.7'
services:
  rickandmorty-api:
    container_name: rickandmorty-api
    build:
      dockerfile: Dockerfile
    image: rickandmorty-api:latest
    ports:
      - 8080:8080
    environment:
      - BASEURL=https://rickandmortyapi.com/
